export const BOARD_CONFIG = {
  VIEW_WIDTH: 1000,
  VIEW_HEIGHT: 800,
  FRAME_WIDTH: 20,
  POINT_HEIGHT_RATIO: 2 / 5,
}

export function calculateBoardDimensions() {
  const BOARD_WIDTH = BOARD_CONFIG.VIEW_WIDTH - (2 * BOARD_CONFIG.FRAME_WIDTH)
  const BOARD_HEIGHT = BOARD_CONFIG.VIEW_HEIGHT - (2 * BOARD_CONFIG.FRAME_WIDTH)
  const POINT_WIDTH = BOARD_WIDTH / 13
  const BAR_WIDTH = POINT_WIDTH
  const POINT_HEIGHT = BOARD_HEIGHT * BOARD_CONFIG.POINT_HEIGHT_RATIO
  const BAR_X_START_RELATIVE = BOARD_WIDTH / 2 - BAR_WIDTH / 2

  return { BOARD_WIDTH, BOARD_HEIGHT, POINT_WIDTH, BAR_WIDTH, POINT_HEIGHT, BAR_X_START_RELATIVE }
}
